import { RuleDefinition } from '../types';

export const BID_INVALIDITY_RULES: RuleDefinition[] = [
  {
    id: 'J1',
    name: '先行谈判+影响中标结果',
    description: '招标人违反规定与投标人就投标价格、方案等实质性内容先行谈判，且影响中标结果',
    category: 'bid-invalidity',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '最高法判例',
    legalSource: 'Ctba司法判例库',
    reasoning: '近半数中标无效案件因此被确认，占比最高的违法类型',
    confidence: 'high',
    note: '该条款适用的前提是必须招标项目，且要求谈判行为确实影响了中标结果',
    uiNote: '🔴 高风险：存在先行谈判行为',
  },
  {
    id: 'J2',
    name: '价格高度雷同+招标前履约',
    description: '中标结果的合同总价与招投标前已签订合同总价基本一致，且招标前已开始施工',
    category: 'bid-invalidity',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '最高法判例',
    legalSource: 'Kangdalawyers判例分析',
    reasoning: '价格高度雷同+招标前实质性履约行为=串通投标强证据',
    confidence: 'high',
    uiNote: '🔴 高风险：价格高度雷同+招标前履约',
  },
  {
    id: 'J3',
    name: '低于成本价投标（存在争议）',
    description: '投标人以低于成本的报价竞标，是否导致合同无效在司法实践中存在争议',
    category: 'bid-invalidity',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第33条',
    legalSource: 'Ctba司法判例库',
    reasoning: '该规定是否属于效力性强制性规定在司法实践中仍存在争议',
    confidence: 'low',
    uiNote: '⚠️ 司法实践存在分歧，仅供参考',
  },
];
