import { RuleDefinition } from '../types';

export const COLLUSION_SIGNAL_RULES: RuleDefinition[] = [
  {
    id: 'C1',
    name: '关联公司同时投标',
    description: '存在股权关联的公司同时参与同一项目投标',
    category: 'collusion-signal',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'medium',
    note: '单纯检测出关联公司同时投标不能直接判定围标，必须叠加报价协同证据',
    uiNote: '🟠 警告：检测到关联公司同时投标',
  },
  {
    id: 'C2',
    name: '投标文件雷同',
    description: '不同投标人的投标文件存在异常相似',
    category: 'collusion-signal',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    confidence: 'high',
    uiNote: '🟠 警告：投标文件存在雷同',
  },
  {
    id: 'C3',
    name: '投标报价异常一致',
    description: '不同投标人的投标报价异常一致或呈规律性变化',
    category: 'collusion-signal',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'statistical',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '山东省宁津县2012年围标串标案例',
    confidence: 'high',
    uiNote: '🔴 高风险：投标报价异常一致',
  },
  {
    id: 'C4',
    name: '招标人泄露信息',
    description: '招标人可能存在泄露标底或投标人信息的行为',
    category: 'collusion-signal',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'ai-semantic',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'medium',
    note: '检测难度较高，可做成提示清单',
    uiNote: '🔴 高风险：可能存在信息泄露',
  },
  {
    id: 'C5',
    name: '投标前已有履约行为',
    description: '中标方在招标前已开始进场施工或提供服务',
    category: 'collusion-signal',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'timeline',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '最高法判例（Kangdalawyers分析）',
    confidence: 'high',
    uiNote: '🔴 高风险：投标前已有履约行为',
  },
];
