import { RuleDefinition } from '../types';

export const ELECTRONIC_FINGERPRINT_RULES: RuleDefinition[] = [
  {
    id: 'T1',
    name: '同一电脑制作',
    description: '不同投标人的电子投标文件由同一台电脑制作',
    category: 'electronic-fingerprint',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '三门县公共资源交易中心规定',
    legalSource: 'Sanmen地方规定',
    confidence: 'high',
    note: '可通过电子招投标平台技术筛查识别',
    uiNote: '🔴 高风险：电子标书指纹异常',
  },
  {
    id: 'T2',
    name: '同一预算编制软件密码锁',
    description: '不同投标人的投标报价用同一个预算编制软件密码锁制作',
    category: 'electronic-fingerprint',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '三门县公共资源交易中心规定',
    legalSource: 'Sanmen地方规定',
    confidence: 'high',
    note: '同一软件密码锁=同一人操作的强证据',
    uiNote: '🔴 高风险：预算软件指纹异常',
  },
  {
    id: 'T3',
    name: '技术文件内容雷同',
    description: '不同投标人的技术文件经查重分析内容异常一致或实质性相同',
    category: 'electronic-fingerprint',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '三门县公共资源交易中心规定',
    legalSource: 'Sanmen地方规定',
    confidence: 'high',
    threshold: {
      id: 'technicalDocumentSimilarity',
      value: 70,
      unit: '%',
      comparison: 'gt',
      source: 'user-confirmed',
    },
    uiNote: '🟠 警告：技术文件相似度超过70%',
  },
  {
    id: 'T4',
    name: '投标报名IP地址一致',
    description: '不同投标人的投标报名IP地址一致，或IP地址在某一特定区域',
    category: 'electronic-fingerprint',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '三门县公共资源交易中心规定',
    legalSource: 'Sanmen地方规定',
    confidence: 'high',
    note: 'IP地址一致=同一地点操作的证据',
    uiNote: '🟠 警告：投标报名IP地址异常',
  },
  {
    id: 'T5',
    name: '投标文件错误一致',
    description: '不同投标人编制的投标文件存在两处以上错误一致',
    category: 'electronic-fingerprint',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'metadata',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '反围标反串标规定',
    legalSource: 'Fanwubi规定',
    confidence: 'high',
    threshold: {
      id: 'bidDocumentErrorCount',
      value: 2,
      unit: '处',
      comparison: 'gte',
      source: 'legal',
    },
    uiNote: '🟠 警告：投标文件存在多处相同错误',
  },
];
