import { RuleDefinition } from '../types';

export const HARD_REJECTION_RULES: RuleDefinition[] = [
  {
    id: 'H1',
    name: '▲实质性要求偏离',
    description: '投标文件中存在▲标记的实质性条款偏离',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第51条',
    confidence: 'high',
    note: '必须代码自动拦截，然后提交动作，留存拦截日志，形成完整风控证据链',
    uiNote: '🔴 废标风险：存在实质性偏离，将自动拦截',
  },
  {
    id: 'H2',
    name: '资格性审查不通过',
    description: '投标人资格条件不符合招标文件要求',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'keyword',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第26条',
    confidence: 'high',
    note: '从招标公示、投标人须知对比',
    uiNote: '🔴 废标风险：资格性审查不通过',
  },
  {
    id: 'H3',
    name: '符合性审查不通过',
    description: '投标文件形式不符合要求（签字、盖章、格式等）',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'regex',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第27条',
    confidence: 'high',
    uiNote: '🔴 废标风险：符合性审查不通过',
  },
  {
    id: 'H4',
    name: '投标有效期不足',
    description: '投标有效期低于招标文件要求',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'numeric-compare',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第29条',
    confidence: 'high',
    uiNote: '🔴 废标风险：投标有效期不足',
  },
  {
    id: 'H5',
    name: '投标文件逾期送达',
    description: '投标文件超过截止时间送达',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'timeline',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第28条',
    confidence: 'high',
    uiNote: '🔴 废标风险：投标文件逾期送达',
  },
  {
    id: 'H6',
    name: '缺少必须资质证书',
    description: '企业资质证书缺失（从招标公示、投标人须知对比）',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'keyword',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第26条',
    confidence: 'high',
    note: '仅看招标公示、投标人须知中的企业资质要求；评分标准中的资质证书只跟扣分相关，不触发此规则',
    uiNote: '🔴 废标风险：缺少必须资质证书',
  },
  {
    id: 'H7',
    name: '★实质性否决项偏离',
    description: '投标文件中标记为★的实质性否决项存在偏离',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第51条',
    confidence: 'high',
    note: '★=实质性否决项，直接废标，投标出局；必须100%完全响应，零偏离；需读招标文件符号释义确认',
    uiNote: '🔴 废标风险：★实质性否决项偏离，将直接废标',
  },
  {
    id: 'H8',
    name: '*实质性否决项偏离',
    description: '投标文件中标记为*的实质性否决项存在偏离（需确认招标文件符号释义）',
    category: 'hard-rejection',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第51条',
    confidence: 'medium',
    note: '*多数情况直接废标，仅标记核心产品时不废标；优先按否决项严格对待，以文件说明为准',
    uiNote: '🔴 废标风险：*实质性否决项偏离，多数情况直接废标',
  },
];
