import { RuleDefinition } from '../types';

export const NUMERIC_THRESHOLD_RULES: RuleDefinition[] = [
  {
    id: 'R01',
    name: '投标保证金占比',
    description: '投标保证金不得超过招标项目估算价的2%',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'bidBondMax',
      value: 2,
      unit: '%',
      comparison: 'lte',
      source: 'legal',
      legalBasis: '《招标投标法实施条例》第26条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第26条',
    confidence: 'high',
    uiNote: '🟡 提示：投标保证金超过法定上限',
  },
  {
    id: 'R02',
    name: '履约保证金占比',
    description: '履约保证金不得超过中标合同金额的10%',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'performanceBondMax',
      value: 10,
      unit: '%',
      comparison: 'lte',
      source: 'legal',
      legalBasis: '《招标投标法实施条例》第58条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第58条',
    confidence: 'high',
    uiNote: '🟡 提示：履约保证金超过法定上限',
  },
  {
    id: 'R03',
    name: '合同追加比例',
    description: '合同追加金额不得超过原合同金额的10%',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'contractAdditionMax',
      value: 10,
      unit: '%',
      comparison: 'lte',
      source: 'legal',
      legalBasis: '《招标投标法》第46条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第46条',
    confidence: 'high',
    uiNote: '🟡 提示：合同追加比例超过法定上限',
  },
  {
    id: 'R04',
    name: '招标文件发售期',
    description: '招标文件发售期不得少于5个工作日',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'tenderDocumentSalePeriod',
      value: 5,
      unit: '工作日',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法》第24条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第24条',
    confidence: 'high',
    uiNote: '🟡 提示：招标文件发售期不足',
  },
  {
    id: 'R05',
    name: '投标截止期限',
    description: '投标截止日期不得少于招标文件发出之日起20日',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'bidDeadline',
      value: 20,
      unit: '日',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法》第24条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第24条',
    confidence: 'high',
    uiNote: '🟡 提示：投标截止期限不足',
  },
  {
    id: 'R06',
    name: '异议答复期',
    description: '异议答复期根据项目类型不同',
    category: 'numeric-threshold',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'engineeringObjectionPeriod',
      value: 3,
      unit: '自然日',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法实施条例》第22条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第22条、财政部94号令',
    confidence: 'high',
    note: '工程招投标3自然日，政府采购7工作日',
    uiNote: '🟡 提示：异议答复期',
  },
  {
    id: 'R07',
    name: '投诉时效',
    description: '投诉时效根据项目类型不同',
    category: 'numeric-threshold',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'engineeringComplaintPeriod',
      value: 10,
      unit: '自然日',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法实施条例》第60条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第60条、财政部94号令',
    confidence: 'high',
    note: '工程招投标10自然日，政府采购15工作日',
    uiNote: '🟡 提示：投诉时效',
  },
  {
    id: 'R08',
    name: '投标有效期',
    description: '投标有效期根据招标文件要求',
    category: 'numeric-threshold',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'validityPeriod',
      value: 0,
      unit: '天',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法》第29条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第29条',
    confidence: 'high',
    note: '无默认值，必须从招标文件提取',
    uiNote: '🟡 提示：投标有效期',
  },
  {
    id: 'R09',
    name: '评标委员会人数',
    description: '评标委员会人数根据项目类型不同',
    category: 'numeric-threshold',
    riskLevel: 'high',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'mandatoryBiddingCommitteeMin',
      value: 5,
      unit: '人',
      comparison: 'gte',
      source: 'legal',
      legalBasis: '《招标投标法》第37条',
    },
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第37条',
    confidence: 'high',
    note: '强制招标≥5人，非强制招标≥3人',
    uiNote: '🟡 提示：评标委员会人数不足',
  },
  {
    id: 'R10',
    name: '价格分权重',
    description: '价格分权重根据招标文件要求',
    category: 'numeric-threshold',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    threshold: {
      id: 'priceWeight',
      value: 0,
      unit: '%',
      comparison: 'gte',
      source: 'legal',
    },
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    note: '无默认值，不同项目差异大（10%-50%）',
    uiNote: '🟡 提示：价格分权重',
  },
];
