import { RuleDefinition } from '../types';

export const PRICE_ANOMALY_RULES: RuleDefinition[] = [
  {
    id: 'P1',
    name: '报价汇总表高度相似',
    description: '三家企业标书中的投标报价汇总表相似程度非常高，尤其表现为报价一致',
    category: 'price-anomaly',
    riskLevel: 'critical',
    interactionType: 'popup-confirm',
    detectionMethod: 'statistical',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '行政处罚案例',
    legalSource: '山东省宁津县2012年案例',
    confidence: 'high',
    threshold: {
      id: 'priceDifferenceThreshold',
      value: 2,
      unit: '%',
      comparison: 'lt',
      source: 'judicial',
    },
    uiNote: '🔴 高风险：报价汇总表高度相似',
  },
  {
    id: 'P2',
    name: '报价呈规律性变化',
    description: '不同投标人的投标报价或报价组成异常一致或呈规律性变化',
    category: 'price-anomaly',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'statistical',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '反围标反串标规定',
    legalSource: 'Fanwubi规定',
    confidence: 'high',
    note: '不能只查完全一致，还要查是否存在等差/等比等人为构造的规律',
    uiNote: '🟠 警告：报价呈规律性变化',
  },
  {
    id: 'P3',
    name: '不平衡报价',
    description: '通过清单报价数据一致性检查、不平衡报价分析检测异常',
    category: 'price-anomaly',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'statistical',
    industries: ['建筑工程'],
    regions: ['全国'],
    legalBasis: '上海宝钢自动评标平台实践',
    legalSource: 'Gsei行业实践',
    confidence: 'medium',
    threshold: {
      id: 'unbalancedBidThreshold',
      value: 30,
      unit: '%',
      comparison: 'gt',
      source: 'industry',
    },
    uiNote: '🟡 提示：存在不平衡报价',
  },
];
