import { RuleDefinition } from '../types';

export const SOFT_REJECTION_RULES: RuleDefinition[] = [
  {
    id: 'R1',
    name: '▲重要打分项负偏离扣分风险',
    description: '▲标记的重要打分项存在负偏离，可能导致高额扣分',
    category: 'soft-rejection',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法实施条例》第51条',
    confidence: 'high',
    weight: 30,
    note: '触发条件：▲项负偏离数量 × 单项扣分 > 该项满分的30%；扣分比例 > 30% 触发high，> 60% 触发critical',
    uiNote: '🟠 风险提示：▲重要打分项负偏离，可能导致高额扣分',
  },
  {
    id: 'R2',
    name: '技术分占比过高风险',
    description: '技术分占总分比例过高，技术方案质量要求高，投入大',
    category: 'soft-rejection',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'numeric-compare',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    weight: 20,
    note: '触发条件：technicalScore / totalScore > 40% → high，> 25% → medium',
    uiNote: '🟠 风险提示：技术分占比过高，需考虑企业是否能在投标截止时间内做出高质量技术方案',
  },
  {
    id: 'R3',
    name: '价格分占比过低风险',
    description: '价格分占总分比例过低，价格竞争空间小',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    weight: 5,
    note: '触发条件：priceScore / totalScore < 10% → medium，>= 10% → low',
    uiNote: '🟡 提示：价格分占比过低，价格竞争空间有限',
  },
  {
    id: 'R4',
    name: '资质证书缺失风险',
    description: '评分标准要求的资质证书缺失，可能影响评分',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'popup-confirm',
    detectionMethod: 'keyword',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第26条',
    confidence: 'high',
    weight: 25,
    note: '仅评分标准要求的证书，非投标人须知中的企业资质；影响废标 → high，仅扣分 → medium',
    uiNote: '🟠 风险提示：缺少评分标准要求的资质证书，可能影响评分',
  },
  {
    id: 'R5',
    name: '业绩要求不足风险',
    description: '类似业绩要求不足，可能影响商务分',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'popup-confirm',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    weight: 15,
    note: '招标文件未写明什么样的合同才计算为业绩时，需提示投标人电话甲方确认',
    uiNote: '🟡 风险提示：业绩要求不足，需确认业绩认定标准',
  },
  {
    id: 'R6',
    name: '交付周期紧张风险',
    description: '项目实施周期紧张，可能影响项目质量和进度',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'ai-semantic',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'medium',
    weight: 10,
    note: '触发条件：winningDeliveryTime 描述的工期 < 项目复杂度所需最低工期',
    uiNote: '🟡 提示：交付周期紧张，需合理安排项目实施计划',
  },
  {
    id: 'R7',
    name: '预算/最高限价异常风险',
    description: '预算金额与最高限价差距异常，利润空间存疑',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'numeric-compare',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    weight: 10,
    note: '触发条件：budget 和 maxPrice 差距 > 20%，或 maxPrice < budget × 0.8',
    uiNote: '🟡 提示：预算/最高限价异常，利润空间可能受限',
  },
  {
    id: 'R8',
    name: '时间紧迫风险',
    description: '距投标截止时间不足，投标准备时间紧张',
    category: 'soft-rejection',
    riskLevel: 'high',
    interactionType: 'popup-confirm',
    detectionMethod: 'timeline',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'high',
    weight: 20,
    note: '触发条件：bidOpeningTime - 当前时间 < 7天 → medium，< 3天 → high',
    uiNote: '🟠 风险提示：距投标截止时间不足，投标准备时间紧张',
  },
  {
    id: 'R9',
    name: '投标文件份数/密封要求复杂',
    description: '投标文件份数或密封包装要求复杂，文件制作失误风险',
    category: 'soft-rejection',
    riskLevel: 'low',
    interactionType: 'display-only',
    detectionMethod: 'ai-semantic',
    industries: ['通用'],
    regions: ['全国'],
    confidence: 'medium',
    weight: 5,
    note: '触发条件：sealingRequirements 或 originalCopies 包含复杂要求',
    uiNote: '🟢 提示：投标文件份数/密封要求较复杂，需仔细核对',
  },
  {
    id: 'R10',
    name: '联合体投标风险',
    description: '联合体投标增加协调和管理难度',
    category: 'soft-rejection',
    riskLevel: 'medium',
    interactionType: 'banner-check',
    detectionMethod: 'combined',
    industries: ['通用'],
    regions: ['全国'],
    legalBasis: '《招标投标法》第31条',
    confidence: 'high',
    weight: 10,
    note: '触发条件：jointBid = true 且我方选择联合体方式；依据《招标投标法》第31条、国资委《国有企业采购内控管理指引》、财政部政府采购内控风险分级模板',
    uiNote: '🟡 提示：联合体投标增加协调成本，需提前规划分工和责任',
  },
];
